# Generated by Django 4.2.5 on 2023-09-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hallucination", "0002_sight_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="vision",
            name="artist",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="vision",
            name="composer",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="sight",
            name="command",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
