# Generated by Django 4.2.5 on 2023-09-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hallucination", "0003_vision_artist_vision_composer_alter_sight_command"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vision",
            name="artist",
            field=models.CharField(default="anonymous", max_length=200),
        ),
        migrations.AlterField(
            model_name="vision",
            name="composer",
            field=models.CharField(default="anonymous", max_length=200),
        ),
    ]
